version: "3"
services:
  wssh:
    build: .
    image: zongzw/webssh:1.0.0
    ports:
     - 4433:4433
    volumes:
     - ./certs:/certs
    entrypoint:
     - wssh 
     - --port=4433
     - --certfile=/certs/domain.crt 
     - --keyfile=certs/domain.key 
     - --fbidhttp=False
     - --maxconn 50
